scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
          - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: $(CLOUD_API_KEY)
      password: $(CLOUD_API_SECRET)
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - $(RESOURCE_KAFKA_ID)
